SELECT     
icustay_id, subject_id, hadm_id, drug, STARTDATE, enddate, drug_name_generic, DOSE_VAL_RX as dose , DOSE_UNIT_RX as unit,route, 
case when  ( ---- 'Benzodiazepines'
   lower(DRUG) Like '%midaz%' or lower(DRUG) Like '%lora%'  or  lower(DRUG) Like '%diazepam%'  or lower(DRUG) Like '%oxazepam%' or   lower(DRUG) Like '%alprazonam%' or  lower(DRUG) Like '%clonazepam%' or  lower(DRUG) Like '%clorazepate%' or  lower(DRUG) Like '%estazolam%' or  lower(DRUG) Like '%flurazepam%' or  lower(DRUG) Like '%temazepam%' or  lower(DRUG) Like '%triazolam%' or  lower(DRUG) Like '%quazepam%' or  lower(DRUG) Like '%versed%' or  lower(DRUG) Like '%ativan%' or  lower(DRUG) Like '%valium%' or  lower(DRUG) Like '%serax%' or  lower(DRUG) Like '%xanax%' or  lower(DRUG) Like '%klonopin%' or  lower(DRUG) Like '%tranzene%' or  lower(DRUG) Like '%prosom%' or  lower(DRUG) Like '%dalmane%' or  lower(DRUG) Like '%restoril%' or  lower(DRUG) Like '%halcion%' or  lower(DRUG) Like '%doral%' ) then 1 else 0 end as benzodiazepines ,
   
case when ( lower(DRUG) Like '%carbinoxamine%' or  lower(DRUG) Like '%arbinoxa%' or  lower(DRUG) Like '%arbinoxa%' or  lower(DRUG) Like '%karbinal er%' or  lower(DRUG) Like '%palgic%'  or  lower(DRUG) Like '%clemastine%' or  lower(DRUG) Like '%tavist allergy%' or  lower(DRUG) Like '%cyproheptadine%'  or  lower(DRUG) Like '%dexchlorpheniramine%' or  lower(DRUG) Like '%polaramine%' or  lower(DRUG) Like '%polaramine repetabs%' or  lower(DRUG) Like '%dimenhydrinate%' or  lower(DRUG) Like '%dramamine%' or  lower(DRUG) Like '%diphenhydramine%' or  lower(DRUG) Like '%allermax%' or  lower(DRUG) Like '%bayer pm%'  or  lower(DRUG) Like '%benadryl%' or  lower(DRUG) Like '%excedrin pm%' or  lower(DRUG) Like '%nytol%'  or  lower(DRUG) Like '%sominex%' or  lower(DRUG) Like '%tylenol pm%' or  lower(DRUG) Like '%unisom%' or  lower(DRUG) Like '%doxylamine%' or  lower(DRUG) Like '%aldex an%'    or  lower(DRUG) Like '%meclizine%' or  lower(DRUG) Like '%antivert%' or  lower(DRUG) Like '%bonine%' or  lower(DRUG) Like '%d-vert%' or  lower(DRUG) Like '%dramamine%'  or  lower(DRUG) Like '%pyrilamine%' or  lower(DRUG) Like '%triprolidine%'  or  lower(DRUG) Like '%histex%' or  lower(DRUG) Like '%zymine%' or  lower(DRUG) Like '%tripohist%') then 1 else 0 end as Anticholinergic,

case when ((lower(drug) Like '%propofol%' or  lower(drug) Like '%diprivan%' or  lower(drug) Like '%ketamine%' or  lower(drug) Like '%ketalar%' or  lower(drug) Like '%dexmedetomidine%' or  lower(drug) Like '%precedex%' or  lower(drug) Like '%clonidine%' or  lower(drug) Like '%guanfacine%') ) then 1 else 0 end as sedatives,

case when (lower(drug) Like '%fetanyl%' or  lower(drug) Like '%sublimaze%' or  lower(drug) Like '%duragesic%' or  lower(drug) Like '%oxycodone%' or  lower(drug) Like '%oxycontin%' or  lower(drug) Like '%roxicodone%' or  lower(drug) Like '%oxaydo%' or  lower(drug) Like '%roxybond%' or  lower(drug) Like '%oxyfast%' or  lower(drug) Like '%dazidox%' or  lower(drug) Like '%oxy ir%' or  lower(drug) Like '%oxycontin cr%' or  lower(drug) Like '%intensol%' or  lower(drug) Like '%xtampza er%' or  lower(drug) Like '%eth-oxydose%' or  lower(drug) Like '%percocet%' or  lower(drug) Like '%combunox%' or  lower(drug) Like '%oxycodan%' or  lower(drug) Like '%maxduo%' or  lower(drug) Like '%roxicet%' or  lower(drug) Like '%endodan%' or  lower(drug) Like '%primlev%' or  lower(drug) Like '%morphine%' or  lower(drug) Like '%kadian%' or  lower(drug) Like '%ms contin%' or  lower(drug) Like '%duramorph%' or  lower(drug) Like '%hydromorphone%' or  lower(drug) Like '%dilaudid-hp%' or  lower(drug) Like '%dilaudid-5%' or  lower(drug) Like '%tramadol%' or  lower(drug) Like '%exalgo%' or  lower(drug) Like '%pallodone%' or  lower(drug) Like '%hydrocodone%' or  lower(drug) Like '%hysingla er%' or  lower(drug) Like '%zohydro er%' or  lower(drug) Like '%vantrela er%' or  lower(drug) Like '%buprenorphine%') then 1 else 0 end as opioids,

case when (( lower(drug) Like '%citalopram%' or  lower(drug) Like '%escitalopram%' or  lower(drug) Like '%fluoxetine%' or  lower(drug) Like '%paroxetine%' or  lower(drug) Like '%sertraline%' or  lower(drug) Like '%vilazodone%'  or  lower(drug) Like '%bupropion%' )) then 1 else 0 end as SSRI,

case when ( ( lower(drug) Like '%duloxetine%' or  lower(drug) Like '%venlafaxine%')) then 1 else 0 end as SNRI,
case when (( lower(drug) Like '%gabapentin%'  or  lower(drug) Like '%pregabalin%' )) then 1 else 0 end as Gabapentinoids

FROM `physionet-data.mimiciii_clinical.prescriptions`  
where 
--- only extract from MV
 ( ---- 'Benzodiazepines'
   lower(DRUG) Like '%midaz%' or lower(DRUG) Like '%lora%'  or  lower(DRUG) Like '%diazepam%'  or lower(DRUG) Like '%oxazepam%' or   lower(DRUG) Like '%alprazonam%' or  lower(DRUG) Like '%clonazepam%' or  lower(DRUG) Like '%clorazepate%' or  lower(DRUG) Like '%estazolam%' or  lower(DRUG) Like '%flurazepam%' or  lower(DRUG) Like '%temazepam%' or  lower(DRUG) Like '%triazolam%' or  lower(DRUG) Like '%quazepam%' or  lower(DRUG) Like '%versed%' or  lower(DRUG) Like '%ativan%' or  lower(DRUG) Like '%valium%' or  lower(DRUG) Like '%serax%' or  lower(DRUG) Like '%xanax%' or  lower(DRUG) Like '%klonopin%' or  lower(DRUG) Like '%tranzene%' or  lower(DRUG) Like '%prosom%' or  lower(DRUG) Like '%dalmane%' or  lower(DRUG) Like '%restoril%' or  lower(DRUG) Like '%halcion%' or  lower(DRUG) Like '%doral%' 
or 
---- 'Anticholinergic medications
 lower(DRUG) Like '%carbinoxamine%' or  lower(DRUG) Like '%arbinoxa%' or  lower(DRUG) Like '%arbinoxa%' or  lower(DRUG) Like '%karbinal er%' or  lower(DRUG) Like '%palgic%'  or  lower(DRUG) Like '%clemastine%' or  lower(DRUG) Like '%tavist allergy%' or  lower(DRUG) Like '%cyproheptadine%'  or  lower(DRUG) Like '%dexchlorpheniramine%' or  lower(DRUG) Like '%polaramine%' or  lower(DRUG) Like '%polaramine repetabs%' or  lower(DRUG) Like '%dimenhydrinate%' or  lower(DRUG) Like '%dramamine%' or  lower(DRUG) Like '%diphenhydramine%' or  lower(DRUG) Like '%allermax%' or  lower(DRUG) Like '%bayer pm%'  or  lower(DRUG) Like '%benadryl%' or  lower(DRUG) Like '%excedrin pm%' or  lower(DRUG) Like '%nytol%'  or  lower(DRUG) Like '%sominex%' or  lower(DRUG) Like '%tylenol pm%' or  lower(DRUG) Like '%unisom%' or  lower(DRUG) Like '%doxylamine%' or  lower(DRUG) Like '%aldex an%'    or  lower(DRUG) Like '%meclizine%' or  lower(DRUG) Like '%antivert%' or  lower(DRUG) Like '%bonine%' or  lower(DRUG) Like '%d-vert%' or  lower(DRUG) Like '%dramamine%'  or  lower(DRUG) Like '%pyrilamine%' or  lower(DRUG) Like '%triprolidine%'  or  lower(DRUG) Like '%histex%' or  lower(DRUG) Like '%zymine%' or  lower(DRUG) Like '%tripohist%'
)
or 
------- Sedatives
(lower(drug) Like '%propofol%' or  lower(drug) Like '%diprivan%' or  lower(drug) Like '%ketamine%' or  lower(drug) Like '%ketalar%' or  lower(drug) Like '%dexmedetomidine%' or  lower(drug) Like '%precedex%' or  lower(drug) Like '%clonidine%' or  lower(drug) Like '%guanfacine%') 
----- Opioids 
or ( lower(drug) Like '%fetanyl%' or  lower(drug) Like '%sublimaze%' or  lower(drug) Like '%duragesic%' or  lower(drug) Like '%oxycodone%' or  lower(drug) Like '%oxycontin%' or  lower(drug) Like '%roxicodone%' or  lower(drug) Like '%oxaydo%' or  lower(drug) Like '%roxybond%' or  lower(drug) Like '%oxyfast%' or  lower(drug) Like '%dazidox%' or  lower(drug) Like '%oxy ir%' or  lower(drug) Like '%oxycontin cr%' or  lower(drug) Like '%intensol%' or  lower(drug) Like '%xtampza er%' or  lower(drug) Like '%eth-oxydose%' or  lower(drug) Like '%percocet%' or  lower(drug) Like '%combunox%' or  lower(drug) Like '%oxycodan%' or  lower(drug) Like '%maxduo%' or  lower(drug) Like '%roxicet%' or  lower(drug) Like '%endodan%' or  lower(drug) Like '%primlev%' or  lower(drug) Like '%morphine%' or  lower(drug) Like '%kadian%' or  lower(drug) Like '%ms contin%' or  lower(drug) Like '%duramorph%' or  lower(drug) Like '%hydromorphone%' or  lower(drug) Like '%dilaudid-hp%' or  lower(drug) Like '%dilaudid-5%' or  lower(drug) Like '%tramadol%' or  lower(drug) Like '%exalgo%' or  lower(drug) Like '%pallodone%' or  lower(drug) Like '%hydrocodone%' or  lower(drug) Like '%hysingla er%' or  lower(drug) Like '%zohydro er%' or  lower(drug) Like '%vantrela er%' or  lower(drug) Like '%buprenorphine%'
)
 ------Selective Serotonin Reuptake Inhibitors and Bupropion
or ( lower(drug) Like '%citalopram%' or  lower(drug) Like '%escitalopram%' or  lower(drug) Like '%fluoxetine%' or  lower(drug) Like '%paroxetine%' or  lower(drug) Like '%sertraline%' or  lower(drug) Like '%vilazodone%'  or  lower(drug) Like '%bupropion%' )
   ----- Serotonin-Norepinephrine Reuptake Inhibitor
or ( lower(drug) Like '%duloxetine%' or  lower(drug) Like '%venlafaxine%')
--- Gabapentinoids
or ( lower(drug) Like '%gabapentin%'  or  lower(drug) Like '%pregabalin%' )