name: covid-19
channels:
  - conda-forge
  - defaults
dependencies:
  - pymssql=2.1.4
  - numpy=1.18.1
  - python=3.7
  - sqlalchemy=1.3.3
  - seaborn=0.9.0
  - scikit-learn=0.22.2
  - pandas=1.0.3
  - psycopg2=2.7.6.1
  - matplotlib=3.2.1
  - pytest=4.3.1
  - jupyter=1.0.0
  - lxml=4.3.3
  - tqdm=4.31.1
  - autopep8
  - pylint=2.3.1
  - flake8=3.7.7
  - regex=2019.11.1
  - sympy=1.4
  - pip=20.0.2
  - shap=0.34.0
  - pip:
    - xgboost=1.0.2